#!/usr/bin/env bash
# Auto-generated by src/run_V_2d_day9.py
set -euo pipefail
MFIX="/Users/nelsonpereira/mamba/envs/mfix-26.1.2/bin/mfixsolver"
cd "/Users/nelsonpereira/Documents/GitHub/Personal_Projects/Nuclear/TRISO-CFD/cases/V_2d/day9"
"$MFIX" -f "V_2d_day9.mfx" > run.log 2>&1
