#!/usr/bin/env bash
# Auto-generated by src/run_fb_sweep.py.
# Concurrency: 1 process(es).
set -euo pipefail
MFIX="/Users/nelsonpereira/mamba/envs/mfix-26.1.2/bin/mfixsolver"
export MFIX

echo '=== u0p30_base (U=0.1219 m/s, imax=38 jmax=150) ==='
pushd "/Users/nelsonpereira/Documents/GitHub/Personal_Projects/Nuclear/TRISO-CFD/cases/fb_sweep/u0p30_base" > /dev/null
"$MFIX" -c -f "u0p30_base.mfx" > run.log 2>&1
popd > /dev/null

echo '=== u0p50_base (U=0.2031 m/s, imax=38 jmax=150) ==='
pushd "/Users/nelsonpereira/Documents/GitHub/Personal_Projects/Nuclear/TRISO-CFD/cases/fb_sweep/u0p50_base" > /dev/null
"$MFIX" -c -f "u0p50_base.mfx" > run.log 2>&1
popd > /dev/null

echo '=== u0p70_base (U=0.2843 m/s, imax=38 jmax=150) ==='
pushd "/Users/nelsonpereira/Documents/GitHub/Personal_Projects/Nuclear/TRISO-CFD/cases/fb_sweep/u0p70_base" > /dev/null
"$MFIX" -c -f "u0p70_base.mfx" > run.log 2>&1
popd > /dev/null

echo '=== u0p90_base (U=0.3656 m/s, imax=38 jmax=150) ==='
pushd "/Users/nelsonpereira/Documents/GitHub/Personal_Projects/Nuclear/TRISO-CFD/cases/fb_sweep/u0p90_base" > /dev/null
"$MFIX" -c -f "u0p90_base.mfx" > run.log 2>&1
popd > /dev/null

echo '=== u1p10_base (U=0.4468 m/s, imax=38 jmax=150) ==='
pushd "/Users/nelsonpereira/Documents/GitHub/Personal_Projects/Nuclear/TRISO-CFD/cases/fb_sweep/u1p10_base" > /dev/null
"$MFIX" -c -f "u1p10_base.mfx" > run.log 2>&1
popd > /dev/null

echo '=== u1p30_base (U=0.5280 m/s, imax=38 jmax=150) ==='
pushd "/Users/nelsonpereira/Documents/GitHub/Personal_Projects/Nuclear/TRISO-CFD/cases/fb_sweep/u1p30_base" > /dev/null
"$MFIX" -c -f "u1p30_base.mfx" > run.log 2>&1
popd > /dev/null

echo '=== u1p60_base (U=0.6499 m/s, imax=38 jmax=150) ==='
pushd "/Users/nelsonpereira/Documents/GitHub/Personal_Projects/Nuclear/TRISO-CFD/cases/fb_sweep/u1p60_base" > /dev/null
"$MFIX" -c -f "u1p60_base.mfx" > run.log 2>&1
popd > /dev/null

echo '=== u2p00_base (U=0.8124 m/s, imax=38 jmax=150) ==='
pushd "/Users/nelsonpereira/Documents/GitHub/Personal_Projects/Nuclear/TRISO-CFD/cases/fb_sweep/u2p00_base" > /dev/null
"$MFIX" -c -f "u2p00_base.mfx" > run.log 2>&1
popd > /dev/null
