"""Generate the Day-9 V_2d spouting-run case directory and a runner script.

Writes:
  cases/V_2d/day9_u1p2/V_2d_day9.mfx     - rendered .mfx (via Jinja2 template)
  cases/V_2d/day9_u1p2/manifest.json     - run provenance (U_in, U_ms, drag, c_e)
  cases/V_2d/day9_u1p2/run.sh            - MFiX runner (writes run.log)

Does not launch MFiX; invoke run.sh (or source it under nohup) explicitly.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from src.make_case import REPO_ROOT, build_V_2d_day9_params, render_case

MFIX_SOLVER = "/Users/nelsonpereira/mamba/envs/mfix-26.1.2/bin/mfixsolver"

DEFAULT_TEMPLATE = REPO_ROOT / "cases" / "V_2d" / "template.mfx.j2"
DEFAULT_RUN_DIR = REPO_ROOT / "cases" / "V_2d" / "day9_u1p2"
RUN_NAME = "V_2d_day9"


def write_runner(run_dir: Path, mfx_name: str) -> Path:
    script = run_dir / "run.sh"
    lines = [
        "#!/usr/bin/env bash",
        "# Auto-generated by src/run_V_2d_day9.py",
        "set -euo pipefail",
        f'MFIX="{MFIX_SOLVER}"',
        f'cd "{run_dir}"',
        f'"$MFIX" -c -f "{mfx_name}" > run.log 2>&1',
        "",
    ]
    script.write_text("\n".join(lines))
    script.chmod(0o755)
    return script


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--template", type=Path, default=DEFAULT_TEMPLATE)
    p.add_argument("--run-dir", type=Path, default=DEFAULT_RUN_DIR)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    params = build_V_2d_day9_params(run_name=RUN_NAME)
    args.run_dir.mkdir(parents=True, exist_ok=True)
    mfx_path = args.run_dir / f"{RUN_NAME}.mfx"

    manifest = {
        "run_name": RUN_NAME,
        "U_in_m_s": params["U_in_m_s"],
        "U_ms_column_m_s": params["U_ms_column_m_s"],
        "u_over_ums": params["u_over_ums"],
        "drag_type": params["drag_type"],
        "c_e": params["c_e"],
        "tstop_s": params["tstop_s"],
        "imax": params["imax"],
        "jmax": params["jmax"],
        "kmax": params["kmax"],
        "mfx": mfx_path.name,
    }
    print(json.dumps(manifest, indent=2))
    if args.dry_run:
        return

    render_case(args.template, params, mfx_path)
    (args.run_dir / "manifest.json").write_text(json.dumps(manifest, indent=2))
    script = write_runner(args.run_dir, mfx_path.name)
    print(f"wrote: {mfx_path}")
    print(f"wrote: {args.run_dir / 'manifest.json'}")
    print(f"wrote: {script}")


if __name__ == "__main__":
    main()
