"""Generate the Day-10 V_3d (ORNL/UTK Case V) 3D STL run directory.

Writes:
  cases/V_3d/day10/V_3d_day10.mfx    - rendered .mfx (via Jinja2 template)
  cases/V_3d/day10/geometry.stl      - vessel inner-wall STL (surface of revolution)
  cases/V_3d/day10/manifest.json     - run provenance (incl. Day-3 CFL wall-time estimate)
  cases/V_3d/day10/run.sh            - MFiX runner (writes run.log)

Does not launch MFiX; invoke run.sh explicitly.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from src.cfl_check import dt_for_cfl
from src.make_case import REPO_ROOT, build_V_3d_params, render_case
from src.make_stl import build_spouted_bed_stl_implicit

MFIX_SOLVER = "/Users/nelsonpereira/mamba/envs/mfix-26.1.2/bin/mfixsolver"

DEFAULT_TEMPLATE = REPO_ROOT / "cases" / "V_3d" / "template.mfx.j2"
DEFAULT_RUN_DIR = REPO_ROOT / "cases" / "V_3d" / "day10"
RUN_NAME = "V_3d_day10"
TSTOP_S = 5.5
U_IN_M_S = 30.0


def write_runner(run_dir: Path, mfx_name: str) -> Path:
    script = run_dir / "run.sh"
    lines = [
        "#!/usr/bin/env bash",
        "# Auto-generated by src/run_V_3d_day10.py",
        "set -euo pipefail",
        f'MFIX="{MFIX_SOLVER}"',
        f'cd "{run_dir}"',
        f'"$MFIX" -f "{mfx_name}" > run.log 2>&1',
        "",
    ]
    script.write_text("\n".join(lines))
    script.chmod(0o755)
    return script


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--template", type=Path, default=DEFAULT_TEMPLATE)
    p.add_argument("--run-dir", type=Path, default=DEFAULT_RUN_DIR)
    p.add_argument("--tstop", type=float, default=TSTOP_S,
                   help=f"simulated end time [s] (default {TSTOP_S})")
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    params = build_V_3d_params(
        U_in_m_s=U_IN_M_S, tstop_s=args.tstop, run_name=RUN_NAME,
        description="Day 10 V_3d (ORNL/UTK Case V, 3D STL cut-cell)",
    )
    args.run_dir.mkdir(parents=True, exist_ok=True)
    mfx_path = args.run_dir / f"{RUN_NAME}.mfx"
    stl_path = args.run_dir / params["stl_filename"]

    # CFL wall-time estimate (CLAUDE.md rule 14, Day-3 tool).  Use the
    # smallest (near-axis) cell size to get the most restrictive explicit dt
    # bound; the actual MFiX run is semi-implicit, so this is a loose upper
    # bound only (compared to the observed Day-9 adaptive dt range of
    # 1e-4 .. 1e-3 s on the planar slab).
    dx_min_m = min(min(params["dx_m_list"]), min(params["dz_m_list"]))
    dt_cfl = dt_for_cfl(u_max=U_IN_M_S, dx=dx_min_m, cfl_target=0.5)
    n_cells = params["imax"] * params["jmax"] * params["kmax"]
    n_steps_approx = int(args.tstop / dt_cfl)

    manifest = {
        "run_name": RUN_NAME,
        "case": "V_3d (ORNL/UTK, 3D STL cut-cell)",
        "U_in_m_s": params["U_in_m_s"],
        "tstop_s": params["tstop_s"],
        "imax": params["imax"],
        "jmax": params["jmax"],
        "kmax": params["kmax"],
        "n_cells_total": n_cells,
        "dx_min_m": dx_min_m,
        "H_static_m": params["H_static_m"],
        "H_dom_m": params["H_dom_m"],
        "L_stub_m": params["L_stub_m"],
        "eps_s_bed": params["eps_s_bed"],
        "ep_star": params["ep_star"],
        "solids_model": "PIC",
        "drag_type": params["drag_type"],
        "friction_model": params["friction_model"],
        "fric_exp_pic": params["fric_exp_pic"],
        "fric_non_sing_fac": params["fric_non_sing_fac"],
        "psfac_fric_pic": params["psfac_fric_pic"],
        "mppic_coeff_en1": params["mppic_coeff_en1"],
        "mppic_coeff_en_wall": params["mppic_coeff_en_wall"],
        "mppic_coeff_et_wall": params["mppic_coeff_et_wall"],
        "mppic_velfac_coeff": params["mppic_velfac_coeff"],
        "des_epg_clip": params["des_epg_clip"],
        "des_interp_scheme": params["des_interp_scheme"],
        "ic_pic_const_statwt": params["ic_pic_const_statwt"],
        "bc_pic_mi_const_statwt": params["bc_pic_mi_const_statwt"],
        "rho_g_kg_m3": params["rho_g_kg_m3"],
        "mu_g_pa_s": params["mu_g_pa_s"],
        "monitor_dt_s": params["monitor_dt_s"],
        "cfl_dt_estimate_s": dt_cfl,
        "approx_total_steps_explicit": n_steps_approx,
        "mfx": mfx_path.name,
        "stl": stl_path.name,
    }
    print(json.dumps(manifest, indent=2))
    if args.dry_run:
        return

    # Day-10 fix 3: generate the STL via implicit-boolean sampling + marching
    # cubes rather than the Day-8 surface-of-revolution helper.  The
    # surface-of-revolution STL has facets only on the vessel wall (and
    # the stub-tube sidewall), so the near-axis cells inside the vessel
    # have no facet-adjacent corners anywhere -- MFiX's F_AT cut-cell
    # classifier (cartesian_grid/intersect.f) then leaves those cells
    # UNDEFINED and marks them BLOCKED.  Three prior fix attempts
    # (JKI propagation, set_corner_cells, stub tube) all left the fluid-
    # cell count stuck at <= 5454 vs the 7770 target.
    #
    # The NETL pic/spouted_bed_3d tutorial sidesteps this with a dense,
    # watertight STL built from a sampled signed-distance function.  Fix 3
    # replicates that approach: sample the vessel SDF (union of stub +
    # cone + freeboard primitives) on a 0.5 mm grid, extract the zero
    # isosurface via marching cubes (PyVista), and rewrite the triangles
    # through _write_ascii_stl so the output is MFiX-standard ASCII with
    # outward-pointing normals.  The resulting STL is closed (bottom and
    # top caps included); MFiX cuts the MI through the bottom cap and
    # the PO through the top cap via its own BC-region logic.
    build_spouted_bed_stl_implicit(
        R_c_m=params["R_c_m"],
        R_i_m=params["R_i_m"],
        cone_half_angle_deg=params["cone_half_angle_deg"],
        H_dom_m=params["H_dom_m"],
        L_stub_m=params["L_stub_m"],
        dx_sample_m=params["dx_sample_m"],
        out_path=stl_path,
    )

    # Count facets in the generated STL for provenance.
    with stl_path.open("r") as _f:
        facet_count = sum(1 for _ln in _f if "facet normal" in _ln)
    manifest["dx_sample_m"] = params["dx_sample_m"]
    manifest["facet_count"] = facet_count

    render_case(args.template, params, mfx_path)
    (args.run_dir / "manifest.json").write_text(json.dumps(manifest, indent=2))
    script = write_runner(args.run_dir, mfx_path.name)
    print(f"wrote: {stl_path}")
    print(f"wrote: {mfx_path}")
    print(f"wrote: {args.run_dir / 'manifest.json'}")
    print(f"wrote: {script}")


if __name__ == "__main__":
    main()
