"""Generate every run directory of the Day 6-7 fb_sweep sweep and emit a
sequential-run shell script.

Each run directory under ``cases/fb_sweep/`` gets a rendered ``.mfx`` named
after its ratio-and-mesh key (e.g. ``u0p70_base.mfx``) plus a short README.

This module does not launch MFiX itself (CLAUDE.md "explain before changing"
discourages hidden long-running work from a script).  Running is explicit:

    bash cases/fb_sweep/run_all.sh    # sequential, writes per-run logs
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

from src.correlations import umf_wen_yu
from src.gasprops import gas_props
from src.make_case import (
    REPO_ROOT,
    _load_yaml,
    build_fb_sweep_params,
    render_case,
)


MFIX_SOLVER = "/Users/nelsonpereira/mamba/envs/mfix-26.1.2/bin/mfixsolver"


def _slug(ratio: float, mesh_tag: str) -> str:
    """Compact tag per run, e.g. 0.7 base -> 'u0p70_base'."""
    s = f"{ratio:.2f}".replace(".", "p")
    return f"u{s}_{mesh_tag}"


def plan_sweep() -> list[dict]:
    """Return the full list of per-run specs: U, mesh, tstop, run_name, out_mfx."""
    particles = _load_yaml(REPO_ROOT / "params" / "particles.yaml")
    geometry = _load_yaml(REPO_ROOT / "params" / "geometry.yaml")
    gases = _load_yaml(REPO_ROOT / "params" / "gases.yaml")

    case_D = particles["case_D"]
    fb = particles["fb_sweep"]
    rig = geometry["fb_sweep_2d"]
    gas_case = gases["cases"][fb["gas_case"]]
    rho_g, mu_g = gas_props(
        gas_case["T_K"], gases["pressure_Pa"], gas_case["composition"]
    )
    umf = umf_wen_yu(case_D["d_p_m"], case_D["rho_p_kg_per_m3"], rho_g, mu_g)

    tstop_s = float(fb["t_startup_s"]) + float(fb["t_avg_s"])

    base_runs = []
    for r in fb["u_over_umf"]:
        base_runs.append(
            dict(
                ratio=float(r),
                U=float(r) * umf,
                imax=int(rig["imax_base"]),
                jmax=int(rig["jmax_base"]),
                mesh="base",
                tstop_s=tstop_s,
            )
        )

    specs = []
    out_root = REPO_ROOT / "cases" / "fb_sweep"
    for spec in base_runs:
        tag = _slug(spec["ratio"], spec["mesh"])
        run_dir = out_root / tag
        run_name = tag
        specs.append(
            dict(
                tag=tag,
                run_dir=run_dir,
                run_name=run_name,
                mfx_path=run_dir / f"{tag}.mfx",
                **spec,
            )
        )
    return specs


def write_cases(specs: list[dict], template_path: Path) -> None:
    import json
    for s in specs:
        params = build_fb_sweep_params(
            U_in_m_s=s["U"],
            imax=s["imax"],
            jmax=s["jmax"],
            tstop_s=s["tstop_s"],
            run_name=s["run_name"],
            description=f"fb_sweep {s['mesh']} U/Umf={s['ratio']:.2f}",
        )
        render_case(template_path, params, s["mfx_path"])
        manifest = {
            "tag": s["tag"],
            "ratio": s["ratio"],
            "U": s["U"],
            "mesh": s["mesh"],
            "imax": s["imax"],
            "jmax": s["jmax"],
            "tstop_s": s["tstop_s"],
            "mfx": s["mfx_path"].name,
        }
        (s["run_dir"] / "manifest.json").write_text(json.dumps(manifest, indent=2))


def write_runner_script(specs: list[dict], script_path: Path, parallel: int = 1) -> None:
    """Write a bash runner.  parallel >= 2 schedules up to that many MFiX processes
    concurrently via ``xargs -P``; parallel == 1 is strictly sequential."""
    lines = [
        "#!/usr/bin/env bash",
        "# Auto-generated by src/run_fb_sweep.py.",
        f"# Concurrency: {parallel} process(es).",
        "set -euo pipefail",
        f'MFIX="{MFIX_SOLVER}"',
        "export MFIX",
        "",
    ]
    if parallel <= 1:
        for s in specs:
            lines += [
                f"echo '=== {s['tag']} (U={s['U']:.4f} m/s, imax={s['imax']} jmax={s['jmax']}) ==='",
                f'pushd "{s["run_dir"]}" > /dev/null',
                f'"$MFIX" -c -f "{s["mfx_path"].name}" > run.log 2>&1',
                "popd > /dev/null",
                "",
            ]
    else:
        # Each line fed to xargs is "<run_dir>|<mfx_name>".
        lines += [
            "run_one() {",
            '    IFS="|" read -r run_dir mfx <<< "$1"',
            '    cd "$run_dir"',
            '    "$MFIX" -c -f "$mfx" > run.log 2>&1',
            '    echo "finished: $run_dir"',
            "}",
            "export -f run_one",
            "",
            "cat <<'JOBS' | xargs -I {} -P " + str(int(parallel)) + " bash -c 'run_one \"$@\"' _ {}",
        ]
        for s in specs:
            lines.append(f"{s['run_dir']}|{s['mfx_path'].name}")
        lines.append("JOBS")
        lines.append("")
    script_path.write_text("\n".join(lines))
    script_path.chmod(0o755)


def _cli() -> None:
    p = argparse.ArgumentParser(description="Generate fb_sweep run directories.")
    p.add_argument(
        "--template",
        type=Path,
        default=REPO_ROOT / "cases" / "fb_sweep" / "template.mfx.j2",
    )
    p.add_argument(
        "--runner-script",
        type=Path,
        default=REPO_ROOT / "cases" / "fb_sweep" / "run_all.sh",
    )
    p.add_argument(
        "--parallel", type=int, default=1,
        help="Number of concurrent MFiX processes to launch (default 1 = serial).",
    )
    p.add_argument(
        "--dry-run", action="store_true", help="Print the plan without writing files."
    )
    args = p.parse_args()

    specs = plan_sweep()
    print(f"Planned {len(specs)} runs:")
    for s in specs:
        print(
            f"  {s['tag']:>14s}  U={s['U']:.4f} m/s  "
            f"imax={s['imax']:>3d} jmax={s['jmax']:>3d}  "
            f"tstop={s['tstop_s']} s"
        )
    if args.dry_run:
        return
    write_cases(specs, args.template)
    write_runner_script(specs, args.runner_script, parallel=args.parallel)
    print(f"Wrote cases under {specs[0]['run_dir'].parent}")
    print(f"Wrote runner script to {args.runner_script}")


if __name__ == "__main__":
    _cli()
